language: node_js
node_js:
  - 10.16.3
cache: npm

install:
  - npm ci
  - npm install -g firebase-tools

script:
  - npm test
  - npm run build

after_success:
  - firebase deploy --project portfoliowebsite-406f5 --token $FIREBASE_TOKEN

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master